### PR TITLE
Replaces norne.tar.gz by re-simulated model with modified schedule file

### PR DESCRIPTION
**Pull request by edubarrosTNO**
Closes https://github.com/equinor/flownet/issues/324

### CODE REVIEW

**Review by wouterjdb — COMMENTED** [review]
Could you test whether it works by creating a PR on the flownet with this flownet-testdata branch?

**Comment by edubarrosTNO** [comment]
> Could you test whether it works by creating a PR on the flownet with this flownet-testdata branch?

I have done so, but the CI is failing due to a bug, see https://github.com/equinor/flownet/issues/326.

**Comment by edubarrosTNO** [comment]
@wouterjdb , all CI checks have passed in test PR https://github.com/equinor/flownet/pull/327. We should be good to merge here - I am requesting a new review now.

**Comment by olelod** [comment]
I ran Flow on my VM with both the new and the original schedule file. Results are very close to (but not exactly) identical. We should be good to go here.

**Review by olelod — APPROVED** [review]
LGTM

**Pull request merged**
